### ISSUE TITLE
"reason": "not support content type(application/json;charset=UTF-8)" 에러 응답

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCCaffeAPIServer#1]
우선 charset을 설정하지 않고 요청하고 있어서 개발에 문제가 있는 것은 아니지만
charset 처리도 고려해보면 좋을 것 같습니다.

Content-Type: application/json;charset=UTF-8
으로 요청하면, 아래와 같이 에러 응답을 수신합니다.
```
{
    "code": 400,
    "reason": "not support content type(application/json;charset=UTF-8)"
}
```

스프링부트에서 같은 고민들이 이미 있네요.
**spring boot mvc - Content type 'application/json;charset=UTF-8' not supported**
https://stackoverflow.com/questions/49005609/spring-boot-mvc-content-type-application-jsoncharset-utf-8-not-supported

규격에서도 Content-Type에 charset 매개변수 지정과 관련된 내용이 있습니다.
**HTTP charset 매개 변수 설정**
https://www.w3.org/International/articles/http-charset/index

**Comment by bojung-dev** [comment]
(참고)
https://www.zerocho.com/category/HTTP/post/5b3ba2d0b3dabd001b53b9db
요청/응답 헤더에 공통으로 사용되는 파라미터 중에서 'Content-' 로 시작하는 헤더를 "엔티티 헤더"라고 부른다.

<엔티티 헤더>
Content-Type
Content-Language
Content-Encoding

**Comment by devdotlog** [comment]
@bojung-dev 
Content-Type 값으로 "application/json" 성공으로 처리하여 문제가 발생을 했습니다. 
"application/json;charset=UTF-8" 도 처리할 수 있도록 변경하도록 하겠습니다.
해당 이슈는 변경하고 서버패치 후에 Close 하도록 하겠습니다.
