### ISSUE TITLE
디지캡, 코비전을 제외한 회사가 추가 될수 있는 상황에 문제

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCCaffeAPIServer#12]
회사 종류에 디지캡, 코비전을 제외한 회사가 추가될 가능성이 있음.
현재 메뉴에 discount는 dc_digicap, dc_covision 으로 사용 중이므로, 회사가 추가될 때마나 D.C. 컬럼이 추가되는 문제가 있음.
이걸 해결하기 위해 우선 DB 구조가 변경되어야 하며, 해당 부분을 사용하는 Caffe Server에 변경이 필요하다.

**Comment by devdotlog** [comment]
discount DB 테이블을 추가한다.
https://github.com/dcblock/wiki/wiki/%EB%8D%B0%EC%9D%B4%ED%83%80%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%A0%95%EC%9D%98

메뉴 테이블에 새로운 메뉴가 입력 될때,  index로 discount에 입력한다.
메뉴 테이블이 SELECT 시점에 equal join으로 처리

**Comment by devdotlog** [comment]
1월 4일 베타 릴리지 이후에 추가될 사항입니다.
"dc_digicap", "dc_covision" 항목을 삭제하고
회사별 discounts 를 추가하였습니다.

@bojung-dev 
(메뉴목록 조회)[https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C] API의 Response 구조 변경

@DevelopDestroyer 
(메뉴삭제)[https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EC%82%AD%EC%A0%9C] API의 Response 구조 변경
(메뉴추가)[https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EC%B6%94%EA%B0%80] / (메뉴수정)[https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EC%88%98%EC%A0%95] API의 Request 구조 변경

**Comment by bojung-dev** [comment]
수정 변경에 동의합니다.
https://github.com/dcblock/wiki/wiki/%EB%8D%B0%EC%9D%B4%ED%83%80%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%A0%95%EC%9D%98#dccaffe-erd

![a](https://github.com/dcblock/wiki/raw/master/images/Erd/DCCaffe%20ERD.png)

**Comment by devdotlog** [comment]
@DevelopDestroyer 
menu CRUD API에서 discounts 부분을 추가 하겠습니다. 
추가로 회사 목록을 위한 CRUD도 필요한데, 이 부분은 일단 회사 목록을 전달하는 API를 추가하겠습니다.

**Comment by bojung-dev** [comment]
API가 변경되면 기능에 문제가 생기는 부분도 같이 반영이되었는지 체크하고 이슈 클로즈해야합니다.

회사 관리를 위해 admin 에서도 company table이 별도로 있어야하며,

웹어드민에서도 그와 맞게 구현이 되어야하므로 큰그림을 합의해서 진행해야할것 같습니다.

수홍과 태호가 해야할 큰그림에 정리해서 작업 스레드를 정리해서 올리겠습니다.

상호는 계획대로 업데이트하면됩니다.

**Comment by bojung-dev** [comment]
company table이 admin과 dcaffe api 두군데에 중복되어 있어야하는 상황이라서 교통정리가 필요합니다.

**Comment by DevelopDestroyer** [comment]
@devdotlog 

이 부분이 고민이네요..

  "discounts": {
    "digicap": 1000,
    "covision": 2000
  }

백오피스 백엔드 단에서도 일단 동적으로 늘었다 줄었다 할 수 있는 dto를 어떻게 정의해서
객체로 만들어야 할 지... 프론트로 라우팅은 어떻게 해야 할지..

**Comment by devdotlog** [comment]
@DevelopDestroyer 
메뉴의 discount를 동적으로 처리하는 기능을 업데이트하였습니다.
영향 받는 API들은 다음의 항목들입니다.
- [메뉴목록조회](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C)
- [메뉴추가](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EC%B6%94%EA%B0%80)
- [메뉴수정](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EB%A9%94%EB%89%B4-%EC%88%98%EC%A0%95)

기존에는 할인금액을 dc_digicap, dc_covision 을 사용했습니다. 이런 부분을 회사들 추가에 따라 
유동적으로 확장/삭제가 가능하도록 아래와 같이 변경하였습니다.
```json
"discounts": {
  "digicap": 1000,
  "covision": 2000
}
```

업데이트는 서버에 반영되어 있습니다.

**Comment by DevelopDestroyer** [comment]
@devdotlog 
네, 변경된 사항에 따라 JSON구조를 백오피스단에서도 조정하였습니다.
확인완료하였고 이상없습니다.
