### ISSUE TITLE
[구매 -> 취소 -> 취소 승인 -> 정산]에 따른 취소 금액이 이월 되었을 경우 시나리오

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCCaffeAPIServer#15]
1월달
구매 후 취소 요청한 금액이 3만원이 되었다.

2월달
취소 요청 건이 최소가 승인되어 -3만원이 되었다.
2월달에 아무것도 안사먹었다.

3월달
-3만원이 이월 되어 정산에 포함되어야 한다.

해당 시나리오에 대한 정산 누락이 발생하는 문제 보완이 필요함

**Comment by devdotlog** [comment]
Caffe API Server는 다음과 같은 순서로 취소금액 이월 경우를 해결
1. 매월 1일 0시 0분 0초에 동작하는 스케줄러에서 실행
2. 지난 달 전체 구매목록에 대한 정산 작업을  수행
3. 구매목록 정산 작업은 사용자 한명, 한명이이 한달 동안 구매한 금액을 계산
4. 사용자가 한달 동안 구매한 가격이 음수가 되면 이번달에 purchage_type=2, receiptid=0, total 가격을 음수로 형태로 추가
