### ISSUE TITLE
구매목록을 전달하는 API의 정렬 대상을 update_date에서 purchase_date로 변경

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCCaffeAPIServer#16]
구매취소목록, 정산목록 등 구매한 목록을 전달하는 API 응답을 update_date 기준으로 역순정렬하여 전달하였습니다. 이것을 태호사원의 요청대로 purchase_date 기준에 역순정렬(최신순)하여 전달하겠습니다.

**Comment by devdotlog** [comment]
다음의 API들이 대상입니다. 서버에는 적용되었습니다.

- 구매취소 목록 조회
- 사용자 구매 목록 조회 
- 정산 목록 조회 
- 사용자의 상세 정산 조회

**Comment by devdotlog** [comment]
@DevelopDestroyer 
서버에 적용되었습니다.

확인 후에 이상 없으면 close 해주세요.

**Comment by DevelopDestroyer** [comment]
확인하였습니다. 이슈를 닫겠습니다.
