### ISSUE TITLE
임시 URL 생성 요청 API - 서비 내부 오류 500 에러 응답

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCCaffeAPIServer#17]
[임시URL 생성요청](https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%9D%BC%ED%9A%8C%EC%9A%A9-%EA%B5%AC%EB%A7%A4%EB%AA%A9%EB%A1%9D-uri-%EC%83%9D%EC%84%B1-%EC%9A%94%EC%B2%AD)

500 내부 시스템 에러가 응답되고 있습니다.
{
  "code": 500,
  "reason": "nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error updating database.  Cause: java.lang.IllegalArgumentException: insert is ambiguous in Mapped Statements collection (try using the full name including the namespace, or rename one of the entries)\n### Cause: java.lang.IllegalArgumentException: insert is ambiguous in Mapped Statements collection (try using the full name including the namespace, or rename one of the entries)"
}

**Comment by devdotlog** [comment]
@bojung-dev 
확인하여 버그 픽그 하였습니다.
