### ISSUE TITLE
WebManager에서 상태를 변경할 수 있는 기능이 필요

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCCaffeAPIServer#20]
WebManager에서 구매상태를 변경할 수 있는 기능은 취소요청 -> 취소완료이 있다.

여기에 추가로 아래의 상태를 변경할 수 있는 기능이 필요하다.
- 취소완료 -> 취소요청(경지실에서 실수로 취소완료를 한 경우)
- 손님결재 -> 월말결재
- 월말결재 -> 손님결재

실수로 구매한 것을 그 자리에서 바로 취소하면 다행이지만 모르고 지나칠 경우에 대한 처리가 필요함
기능상 있으면 좋을 것 같은데. 
이런 경우를 자동으로 처리하게 해주는게 좋은지, 확인 후에 우리가 DB에서 바꾸는게 좋은지 모르겠음

**Comment by devdotlog** [comment]
아래의 기능은 WebManager에서 기능으로 제공하지 않음
- 손님결재 -> 월말결재
- 월말결재 -> 손님결재

**Comment by bojung-dev** [comment]
해당 기능에 대해서는 우선 보류 하겠습니다.
우선 이슈를 닫고, 긴급한 이슈 먼저 처리한 후에 재 논의 하는 것이 좋을 것 같습니다.

키오스크에서 손님결제에 대한 사용자 확인을 위한 UI Feedback을 한번더 확인하고,
현재 손님결제로 진입 했다는 것을 확실히 인식할 수 있도록 보완하는 것으로 대체하겠습니다.
