### ISSUE TITLE
'Menus' 테이블에 "event_name" 필드가 없습니다.

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCCaffeAPIServer#3]
메뉴 속성으로 'EVENT 이름' 추가에 대한 건이 있었는데 확인해서 반영 부탁합니다.
태호사원의 메뉴 관리에서는 "EVENT 이름"을 입력받을 수 있도록 추가해 주세요.
서상호 과장은 "EVENT 이름" 관련해서 업데이트 해주세요.

```
    "Coffee": [
        {
            "category": 100,
            "code": 1,
            "name_kr": "에스프레소",
            "name_en": "espreso",
            "price": 2500,
            "dc_digicap": 1000,
            "dc_covision": 0,
            "event_name": "",
            "type": "BOTH",
            "size": "REGULAR"
        },
```

**Comment by bojung-dev** [comment]
@devdotlog @DevelopDestroyer 

![메뉴 주문 화면](https://github.com/dcblock/wiki/blob/master/images/DCCaffeKiosk/MenuBoard.png?raw=true)

**Comment by DevelopDestroyer** [comment]
백오피스단에서 반영하였습니다.
- 메뉴 리스트 호출 시, 테이블에서 이벤트명을 보여줌
- 메뉴 수정 시, 해당 카테고리의 각 메뉴별 이벤트명을 보여줌
- 메뉴 추가 시, 이벤트명 입력 필드 추가
이슈를 닫겠습니다.
