### ISSUE TITLE
구매 이력이 존재하지만 지정한 기간에 누적 총액이 0원으로 나옵니다.

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCCaffeAPIServer#7]
구매 이력이 purchase에 존재하는데,
응답은 누적 사용 금액이 없다고 합니다.

http://10.1.203.12:8080/api/caffe/purchases/purchase/rfid/C26A1932A19823A8AF176AD8B80CA8AEACDDFFD3DA63695EB12B77534026DD4C?purchaseBefore=1542672000&purchaseAfter=1545310574 

```
{
    "name": "정병옥",
    "total_price": 0,
    "total_dc_price": 0
}
```

**Comment by devdotlog** [comment]
@DevelopDestroyer @bojung-dev 
조회를 위해 CaffeAPIServer에서 제공하는 시간 범위는 규칙은 아래와 같습니다.
before < X < after
